#cloud-config
autoinstall:
  version: 1
  refresh-installer:
    update: yes

  locale: de_DE.UTF-8
  timezone: Europe/Berlin
    
  keyboard:
    layout: de

  identity:
    hostname: newmachine
    password: $6$mdEyp4TqtLB5xite$tzOQdd8KH8nyCJF7B6VcfBXtVO.waHAgE6cIQGopwrddojgBncpz6aWxmUB845V1uqp7rqezN0IOa70q0AZMJ/
    username: phytec

  storage:
    layout:
      name: direct

  ssh:
    allow-pw: true
    install-server: true

  apt:
    primary:
      - arches: [default]
        uri: 'http://de.archive.ubuntu.com/ubuntu/'
        search: 'http://de.archive.ubuntu.com/ubuntu/'

  packages: 
    - language-pack-de-base
    - language-pack-de
    - wngerman
    - gnome-user-docs-de
    - wogerman
    - wswiss
    - language-pack-gnome-de
    - build-essential
    - ubuntu-desktop-minimal
    - sssd
    - sssd-tools
    - samba
    - smbclient
    - cifs-utils
    - libpam-mount
    - libpam-ccreds
    - keyutils
    - hxtools
    - realmd
    - adcli
    - vim
    - unattended-upgrades
    - apt-transport-https
    - wget
    - gnupg
    - git
    - python3
    - x2goserver
    - x2goserver-xsession
    - x2goclient
    - libreoffice
    - gnome-session-flashback
    - vlc
    - krdc
    - terminator

  package_update: true
  package_upgrade: true

  shutdown: poweroff
  
  early-commands:
    - echo 'linux-generic-hwe-22.04' > /run/kernel-meta-package
    
  late-commands:
    # prerequisite to join AD
    - echo "session required pam_mkhomedir.so umask=0022 skel=/etc/skel" >> /target/etc/pam.d/common-session

    # Changing from networkd to NetworkManager
    # move existing config out of the way
    - find /target/etc/netplan/ -name "*.yaml" -exec sh -c 'mv "$1" "$1-orig"' _ {} \;
    # Create a new netplan and enable it
    - |
      cat << EOF | sudo tee /target/etc/netplan/01-netcfg.yaml
      network:
        version: 2
        renderer: NetworkManager
      EOF

    - curtin in-target --target /target netplan generate
    - curtin in-target --target /target netplan apply
    - curtin in-target --target /target systemctl enable NetworkManager.service

    # Enable automatic Upgrades
    - |
      cat << EOF | sudo tee /target/etc/apt/apt.conf.d/20auto-upgrades
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
      EOF

    - |
      cat << EOF | sudo tee /target/etc/apt/apt.conf.d/50unattended-upgrades
      // Automatically upgrade packages from these (origin, archive) pairs
      Unattended-Upgrade::Allowed-Origins {
          // ${distro_id} and ${distro_codename} will be automatically expanded
          "${distro_id} stable";
          "${distro_id} ${distro_codename}-security";
          "${distro_id} ${distro_codename}-updates";
      //  "${distro_id} ${distro_codename}-proposed-updates";
          "ubuntu icinga-${distro_codename} icinga-${distro_codename}"
      };

      // List of packages to not update
      Unattended-Upgrade::Package-Blacklist {
      //  "vim";
      //  "libc6";
      //  "libc6-dev";
      //  "libc6-i686";
      };

      // Do automatic removal of new unused dependencies after the upgrade
      // (equivalent to apt-get autoremove)
      Unattended-Upgrade::Remove-Unused-Dependencies "true";
      EOF
      
    - >-
      curtin in-target -- apt-get remove -y
      ubuntu-server ubuntu-server-minimal
      binutils byobu dmeventd finalrd gawk
      kpartx mdadm ncurses-term needrestart open-iscsi
      sg3-utils thin-provisioning-tools tmux
      sosreport open-vm-tools motd-news-config lxd-agent-loader
      landscape-common
    - curtin in-target -- apt-get install -y cloud-init
    - curtin in-target -- apt-get autoremove -y
